@startuml Encargado
    [*] --> Libre
    Libre --> Cobrando : cobrar()
    Libre --> TomandoPedido : nuevoPedido()
    TomandoPedido --> Libre : listo()
    Libre --> EntregandoComanda : cargarPedido()
    EntregandoComanda --> Libre : comandaEntregada()
    Cobrando -up-> Libre : listo()
    Cobrando --> [*] : ultimoPedido()
@enduml