@startuml Telefono
    [*] --> EsperaDePedido
    EsperaDePedido --> Llamando : sonando()
    Llamando --> EnLlamada: telefonoAtendido()
    Llamando --> EsperaDePedido: llamadaPerdida()
    EnLlamada --> EsperaDePedido : pedidoCargado()
    EnLlamada --> [*] : Timeout()
@endumlx