@startuml Cocinero
    [*] --> EsperaDePedido
    EsperaDePedido --> Ocupado : nuevoPedido()
    EsperaDePedido --> EsperaDePedido : cocineroOcupado()
    Ocupado --> Ocupado : cocinando()
    Ocupado --> EsperaDePedido: entregarPedidoADelivery()
@enduml