@startuml Cocinero
    [*] --> EsperaDePedido
    EsperaDePedido --> EsperaDePedido : esperandoPedido()
    EsperaDePedido --> Ocupado : nuevoPedido()
    Ocupado --> Ocupado : cocinando()
    Ocupado --> Listo : pedidoCocinado()
    Listo --> Listo : deliveryBloqueado()
    Listo --> EsperaDePedido: entregarPedidoADelivery()
@enduml