@startuml Delivery
    [*] --> EsperandoPedido
    EsperandoPedido --> EntregandoPedido : entregarPedido()
    EntregandoPedido --> EntregandoDinero : pedidoEntregado()
    EntregandoDinero --> EsperandoPedido : dineroEntregado()
    EntregandoDinero --> [*] : ultimoPedido()
@endumld