@startuml Delivery
    [*] --> EsperaDePedido
    EsperaDePedido --> EntregandoPedido : nuevoPedido()
    EntregandoPedido --> EntregandoDinero : pedidoEntregado()
    EntregandoDinero --> EsperaDePedido : listo()
    EntregandoDinero --> [*] : finalizado()
@enduml