@startuml Encargado
    [*] --> EsperaDePedido
    EsperaDePedido --> TomandoPedido : nuevoPedido()
    TomandoPedido --> CargandoPedido : pedidoCargado()
    CargandoPedido -up-> Cobrando : cobrar()
    Cobrando -up-> EsperaDePedido : enEsperaLlamada()
    Cobrando --> [*] : ultimoPedido()
@enduml