@startuml Encargado
    [*] --> EsperaDePedido
    EsperaDePedido --> EsperaDePedido : esperandoPedido()
    EsperaDePedido --> Ocupado : nuevoPedido()
    Ocupado --> Ocupado : cargandoPedido()
    Ocupado --> Listo: pedidoCargado()
    Listo --> Listo : cocineroBloqueado()
    Listo --> EsperaDePedido : pedidoTomadoPorCocinero()
@enduml