@startuml Telefono
    [*] --> EsperaDePedido
    EsperaDePedido --> EsperaDePedido : esperandoPedido()
    EsperaDePedido --> Ocupado : nuevoPedido()
    Ocupado --> Ocupado : sonando()
    Ocupado --> Listo: telefonoAtendido()
    Listo --> Listo : cargandoPedido()
    Listo --> EsperaDePedido : pedidoCargado()
@enduml