@startuml Telefono
    [*] --> EsperaDePedido
    EsperaDePedido --> Llamando : nuevoPedido()
    Llamando --> EnLlamada: telefonoAtendido()
    EnLlamada --> EsperaDePedido : pedidoCargado()
@endumlx